
SERVER_FILE = ../Public/Interface.h \
			  ../Public/ErrorHandler.h \
			  ../Public/ErrorHandler.cpp \
			  ../Public/SocketCreator.h \
			  ../Public/SocketCreator.cpp 
					 
SERVER_SOURCE_FILE = ../Public/ErrorHandler.cpp \
					 ../Public/SocketCreator.cpp

PUBLIC_CLIENT_FILE = ../Public/Interface.h \
					 ../Public/ErrorHandler.h \
					 ../Public/ErrorHandler.cpp \
					 ../Public/SocketCreator.h \
					 ../Public/SocketCreator.cpp \
					 ../Public/GetCurrTime.h \
					 ../Public/GetCurrTime.cpp

PUBLIC_CLIENT_SOURCE_FILE = ../Public/ErrorHandler.cpp \
							../Public/SocketCreator.cpp \
							../Public/GetCurrTime.cpp